// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package repository

import (
	"context"
)

const getUsers = `-- name: GetUsers :many
SELECT id, email, phone, name, date_of_birth, profile_pic, email_verified, phone_verified, last_login, account_status, deactivated_at, deactivation_reason, created_at, updated_at from users
`

func (q *Queries) GetUsers(ctx context.Context) ([]*User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Name,
			&i.DateOfBirth,
			&i.ProfilePic,
			&i.EmailVerified,
			&i.PhoneVerified,
			&i.LastLogin,
			&i.AccountStatus,
			&i.DeactivatedAt,
			&i.DeactivationReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
