// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusActive   AccountStatus = "active"
	AccountStatusInactive AccountStatus = "inactive"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type AuthProvider string

const (
	AuthProviderUsername AuthProvider = "username"
	AuthProviderGoogle   AuthProvider = "google"
	AuthProviderPhone    AuthProvider = "phone"
	AuthProviderEmail    AuthProvider = "email"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type AuthIdentity struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	UserID     pgtype.UUID        `db:"user_id" json:"user_id"`
	Provider   AuthProvider       `db:"provider" json:"provider"`
	Identifier string             `db:"identifier" json:"identifier"`
	Verified   *bool              `db:"verified" json:"verified"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Session struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	SchoolID         pgtype.UUID        `db:"school_id" json:"school_id"`
	Provider         AuthProvider       `db:"provider" json:"provider"`
	RefreshTokenHash string             `db:"refresh_token_hash" json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	IsActive         *bool              `db:"is_active" json:"is_active"`
	IpAddress        *string            `db:"ip_address" json:"ip_address"`
	UserAgent        *string            `db:"user_agent" json:"user_agent"`
	DeviceType       *string            `db:"device_type" json:"device_type"`
	DeviceName       *string            `db:"device_name" json:"device_name"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type User struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Email              *string            `db:"email" json:"email"`
	Phone              *string            `db:"phone" json:"phone"`
	Name               string             `db:"name" json:"name"`
	DateOfBirth        pgtype.Date        `db:"date_of_birth" json:"date_of_birth"`
	ProfilePic         *string            `db:"profile_pic" json:"profile_pic"`
	EmailVerified      *bool              `db:"email_verified" json:"email_verified"`
	PhoneVerified      *bool              `db:"phone_verified" json:"phone_verified"`
	LastLogin          pgtype.Timestamptz `db:"last_login" json:"last_login"`
	AccountStatus      NullAccountStatus  `db:"account_status" json:"account_status"`
	DeactivatedAt      pgtype.Timestamptz `db:"deactivated_at" json:"deactivated_at"`
	DeactivationReason *string            `db:"deactivation_reason" json:"deactivation_reason"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
